package com.ecostep.app.ui.mock

import com.ecostep.app.ui.viewmodels.UpcomingMissionUi

enum class MissionDay(
    val shortLabel: String,
    val fullLabel: String,
) {
    MONDAY("Mon", "Monday"),
    TUESDAY("Tue", "Tuesday"),
    WEDNESDAY("Wed", "Wednesday"),
    THURSDAY("Thu", "Thursday"),
    FRIDAY("Fri", "Friday"),
    SATURDAY("Sat", "Saturday"),
    SUNDAY("Sun", "Sunday"),
}

data class MissionTransportOption(
    val label: String,
    val estimatedEcoPoints: Int,
    val estimatedCarbonSavedKg: Double,
)

/**
 * Temporary UI model containing the route, recurring schedule and
 * transport impact options needed by MissionScreen.
 *
 * TODO(Missions): Replace or map this model from the production mission
 * domain model so the UI does not depend on mock-layer data structures.
 */
data class MissionPageItem(
    val mission: UpcomingMissionUi,
    val startLocation: String,
    val destination: String,
    val scheduledHour: Int,
    val scheduledMinute: Int,
    val repeatDays: Set<MissionDay>,
    val explanation: String,
    val transportOptions: List<MissionTransportOption>,
    /** Route distance for the chosen mode, when known. */
    val distanceMeters: Double? = null,
    /** Today's occurrence was already completed; the mission stays listed for its next one. */
    val completedToday: Boolean = false,
    /** Today's occurrence was skipped. */
    val skippedToday: Boolean = false,
    /** Whether the repeating schedule includes today. */
    val dueToday: Boolean = true,
    /** Next scheduled date ("YYYY-MM-DD"), when known. */
    val nextOccurrenceDate: String? = null,
) {
    /** e.g. "Completed today ✓ · Next: Wed 7 Oct"; null when today's occurrence is still open. */
    val todayStatusLabel: String?
        get() {
            val status = when {
                completedToday -> "Completed today ✓"
                skippedToday -> "Skipped today"
                else -> return null
            }
            val next = nextOccurrenceDate
                ?.let { runCatching { java.time.LocalDate.parse(it) }.getOrNull() }
                ?.format(java.time.format.DateTimeFormatter.ofPattern("EEE d MMM", java.util.Locale.getDefault()))
                ?: return status
            return "$status · Next: $next"
        }

    val scheduleLabel: String
        get() {
            val displayHour = when {
                scheduledHour == 0 -> 12
                scheduledHour > 12 -> scheduledHour - 12
                else -> scheduledHour
            }

            val period = if (scheduledHour < 12) "am" else "pm"
            val time = "%d:%02d %s".format(
                displayHour,
                scheduledMinute,
                period,
            )

            val repeatLabel = when {
                repeatDays.size == MissionDay.entries.size ->
                    "Every day"

                repeatDays == setOf(
                    MissionDay.MONDAY,
                    MissionDay.TUESDAY,
                    MissionDay.WEDNESDAY,
                    MissionDay.THURSDAY,
                    MissionDay.FRIDAY,
                ) ->
                    "Weekdays"

                repeatDays.size == 1 ->
                    "Every ${repeatDays.first().fullLabel}"

                else ->
                    repeatDays
                        .sortedBy { it.ordinal }
                        .joinToString(", ") { it.shortLabel }
            }

            return "$repeatLabel at $time"
        }

}


interface MissionScreenDataSource {
    fun getSuggestedMission(): MissionPageItem?

    fun getUpcomingMissions(): List<MissionPageItem>
}

/**
 * Supplies temporary mission data for the UI prototype.
 *
 * TODO(Missions): Replace suggested missions with results generated by
 * MissionGenerator from the signed-in user's recurring journey patterns.
 * Load accepted and upcoming missions through the production
 * Firebase-backed MissionRepository.
 *
 * TODO(Routing/Algorithm): Replace the mock route information and
 * hard-coded transport impact options with route distance and duration
 * from the routing module, then calculate EcoPoints and carbon savings
 * through the production calculators.
 */
class MockMissionScreenDataSource : MissionScreenDataSource {

    override fun getSuggestedMission(): MissionPageItem =
        MissionPageItem(
            mission = UpcomingMissionUi(
                missionId = "mock-suggested-mission",
                routeTitle = "Home → University",
                transportLabel = "Cycling",
                estimatedEcoPoints = 100,
                estimatedCarbonSavedKg = 0.52,
                startTimeMillis = 0L,
                endTimeMillis = 0L,
            ),
            startLocation = "Home",
            destination = "University",
            scheduledHour = 8,
            scheduledMinute = 30,
            repeatDays = setOf(
                MissionDay.MONDAY,
                MissionDay.TUESDAY,
                MissionDay.WEDNESDAY,
                MissionDay.THURSDAY,
                MissionDay.FRIDAY,
            ),
            explanation =
                "This suggestion is based on a frequently repeated journey.",
            transportOptions = listOf(
                MissionTransportOption(
                    label = "Walking",
                    estimatedEcoPoints = 140,
                    estimatedCarbonSavedKg = 0.64,
                ),
                MissionTransportOption(
                    label = "Cycling",
                    estimatedEcoPoints = 100,
                    estimatedCarbonSavedKg = 0.52,
                ),
                MissionTransportOption(
                    label = "Public Transport",
                    estimatedEcoPoints = 70,
                    estimatedCarbonSavedKg = 0.31,
                ),
                MissionTransportOption(
                    label = "Car",
                    estimatedEcoPoints = 0,
                    estimatedCarbonSavedKg = 0.0,
                ),
            ),
        )

    override fun getUpcomingMissions(): List<MissionPageItem> =
        listOf(
            MissionPageItem(
                mission = UpcomingMissionUi(
                    missionId = "mock-upcoming-mission-1",
                    routeTitle = "University → Home",
                    transportLabel = "Public Transport",
                    estimatedEcoPoints = 120,
                    estimatedCarbonSavedKg = 1.4,
                    startTimeMillis = 0L,
                    endTimeMillis = 0L,
                ),
                startLocation = "University",
                destination = "Home",
                scheduledHour = 17,
                scheduledMinute = 0,
                repeatDays = setOf(
                    MissionDay.MONDAY,
                ),
                explanation = "",
                transportOptions = listOf(
                    MissionTransportOption(
                        label = "Walking",
                        estimatedEcoPoints = 160,
                        estimatedCarbonSavedKg = 1.7,
                    ),
                    MissionTransportOption(
                        label = "Cycling",
                        estimatedEcoPoints = 140,
                        estimatedCarbonSavedKg = 1.55,
                    ),
                    MissionTransportOption(
                        label = "Public Transport",
                        estimatedEcoPoints = 120,
                        estimatedCarbonSavedKg = 1.4,
                    ),
                    MissionTransportOption(
                        label = "Car",
                        estimatedEcoPoints = 0,
                        estimatedCarbonSavedKg = 0.0,
                    ),
                ),
            ),
            MissionPageItem(
                mission = UpcomingMissionUi(
                    missionId = "mock-upcoming-mission-2",
                    routeTitle = "Home → Gym",
                    transportLabel = "Walking",
                    estimatedEcoPoints = 80,
                    estimatedCarbonSavedKg = 0.35,
                    startTimeMillis = 0L,
                    endTimeMillis = 0L,
                ),
                startLocation = "Home",
                destination = "Gym",
                scheduledHour = 18,
                scheduledMinute = 0,
                repeatDays = setOf(
                    MissionDay.WEDNESDAY,
                ),
                explanation = "",
                transportOptions = listOf(
                    MissionTransportOption(
                        label = "Walking",
                        estimatedEcoPoints = 80,
                        estimatedCarbonSavedKg = 0.35,
                    ),
                    MissionTransportOption(
                        label = "Cycling",
                        estimatedEcoPoints = 65,
                        estimatedCarbonSavedKg = 0.29,
                    ),
                    MissionTransportOption(
                        label = "Public Transport",
                        estimatedEcoPoints = 40,
                        estimatedCarbonSavedKg = 0.18,
                    ),
                    MissionTransportOption(
                        label = "Car",
                        estimatedEcoPoints = 0,
                        estimatedCarbonSavedKg = 0.0,
                    ),
                ),
            ),
        )
}
